# Generated by Django 4.0.5 on 2023-01-27 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('bio', models.TextField()),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Account Created')),
            ],
        ),
    ]
