# Generated by Django 4.0.5 on 2023-01-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Profile',
        ),
    ]
