# Generated by Django 4.2 on 2023-07-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('social', '0002_profile_is_google_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount'),
        ),
    ]
