# Generated by Django 4.2 on 2023-07-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_socialprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='bio',
            field=models.TextField(blank=True, default='What has four wheels and flies? Garbage truck'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='photo',
            field=models.ImageField(blank=True, default='tanjiro.jpg', upload_to=''),
        ),
    ]
