# Generated by Django 4.2 on 2023-07-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_socialprofile_bio_alter_socialprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='bio',
            field=models.TextField(blank=True, default='Dad, can you put my shoes on? No, I don’t think they’ll fit me.'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='photo',
            field=models.ImageField(blank=True, default='giyu.jpg', upload_to=''),
        ),
    ]
