# Generated by Django 4.2 on 2023-07-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_socialprofile_bio_alter_socialprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='bio',
            field=models.TextField(blank=True, default='There are two types of people in the world, those who can extrapolate from incomplete data.'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='photo',
            field=models.ImageField(blank=True, default='jojo.jpg', upload_to=''),
        ),
    ]
