# Generated by Django 3.2.16 on 2025-04-07 15:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_socialprofile_bio_alter_socialprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='posts')),
                ('caption', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2025, 4, 7, 15, 7, 41, 538078))),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='bio',
            field=models.TextField(blank=True, default='Can February March? No, but April May!'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='photo',
            field=models.ImageField(blank=True, default='giyu.jpg', upload_to=''),
        ),
    ]
